package net.xyt.payment.batch.entity.transrcv;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PayTransRcvRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    public PayTransRcvRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("pkid is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("pkid is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(Long value) {
            addCriterion("pkid =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(Long value) {
            addCriterion("pkid <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(Long value) {
            addCriterion("pkid >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(Long value) {
            addCriterion("pkid >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(Long value) {
            addCriterion("pkid <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(Long value) {
            addCriterion("pkid <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<Long> values) {
            addCriterion("pkid in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<Long> values) {
            addCriterion("pkid not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(Long value1, Long value2) {
            addCriterion("pkid between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(Long value1, Long value2) {
            addCriterion("pkid not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andRcvAcctNoIsNull() {
            addCriterion("rcv_acct_no is null");
            return (Criteria) this;
        }

        public Criteria andRcvAcctNoIsNotNull() {
            addCriterion("rcv_acct_no is not null");
            return (Criteria) this;
        }

        public Criteria andRcvAcctNoEqualTo(String value) {
            addCriterion("rcv_acct_no =", value, "rcvAcctNo");
            return (Criteria) this;
        }

        public Criteria andRcvAcctNoNotEqualTo(String value) {
            addCriterion("rcv_acct_no <>", value, "rcvAcctNo");
            return (Criteria) this;
        }

        public Criteria andRcvAcctNoGreaterThan(String value) {
            addCriterion("rcv_acct_no >", value, "rcvAcctNo");
            return (Criteria) this;
        }

        public Criteria andRcvAcctNoGreaterThanOrEqualTo(String value) {
            addCriterion("rcv_acct_no >=", value, "rcvAcctNo");
            return (Criteria) this;
        }

        public Criteria andRcvAcctNoLessThan(String value) {
            addCriterion("rcv_acct_no <", value, "rcvAcctNo");
            return (Criteria) this;
        }

        public Criteria andRcvAcctNoLessThanOrEqualTo(String value) {
            addCriterion("rcv_acct_no <=", value, "rcvAcctNo");
            return (Criteria) this;
        }

        public Criteria andRcvAcctNoLike(String value) {
            addCriterion("rcv_acct_no like", value, "rcvAcctNo");
            return (Criteria) this;
        }

        public Criteria andRcvAcctNoNotLike(String value) {
            addCriterion("rcv_acct_no not like", value, "rcvAcctNo");
            return (Criteria) this;
        }

        public Criteria andRcvAcctNoIn(List<String> values) {
            addCriterion("rcv_acct_no in", values, "rcvAcctNo");
            return (Criteria) this;
        }

        public Criteria andRcvAcctNoNotIn(List<String> values) {
            addCriterion("rcv_acct_no not in", values, "rcvAcctNo");
            return (Criteria) this;
        }

        public Criteria andRcvAcctNoBetween(String value1, String value2) {
            addCriterion("rcv_acct_no between", value1, value2, "rcvAcctNo");
            return (Criteria) this;
        }

        public Criteria andRcvAcctNoNotBetween(String value1, String value2) {
            addCriterion("rcv_acct_no not between", value1, value2, "rcvAcctNo");
            return (Criteria) this;
        }

        public Criteria andRcvTransAmtIsNull() {
            addCriterion("rcv_trans_amt is null");
            return (Criteria) this;
        }

        public Criteria andRcvTransAmtIsNotNull() {
            addCriterion("rcv_trans_amt is not null");
            return (Criteria) this;
        }

        public Criteria andRcvTransAmtEqualTo(BigDecimal value) {
            addCriterion("rcv_trans_amt =", value, "rcvTransAmt");
            return (Criteria) this;
        }

        public Criteria andRcvTransAmtNotEqualTo(BigDecimal value) {
            addCriterion("rcv_trans_amt <>", value, "rcvTransAmt");
            return (Criteria) this;
        }

        public Criteria andRcvTransAmtGreaterThan(BigDecimal value) {
            addCriterion("rcv_trans_amt >", value, "rcvTransAmt");
            return (Criteria) this;
        }

        public Criteria andRcvTransAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rcv_trans_amt >=", value, "rcvTransAmt");
            return (Criteria) this;
        }

        public Criteria andRcvTransAmtLessThan(BigDecimal value) {
            addCriterion("rcv_trans_amt <", value, "rcvTransAmt");
            return (Criteria) this;
        }

        public Criteria andRcvTransAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rcv_trans_amt <=", value, "rcvTransAmt");
            return (Criteria) this;
        }

        public Criteria andRcvTransAmtIn(List<BigDecimal> values) {
            addCriterion("rcv_trans_amt in", values, "rcvTransAmt");
            return (Criteria) this;
        }

        public Criteria andRcvTransAmtNotIn(List<BigDecimal> values) {
            addCriterion("rcv_trans_amt not in", values, "rcvTransAmt");
            return (Criteria) this;
        }

        public Criteria andRcvTransAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rcv_trans_amt between", value1, value2, "rcvTransAmt");
            return (Criteria) this;
        }

        public Criteria andRcvTransAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rcv_trans_amt not between", value1, value2, "rcvTransAmt");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIsNull() {
            addCriterion("trade_type is null");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIsNotNull() {
            addCriterion("trade_type is not null");
            return (Criteria) this;
        }

        public Criteria andTradeTypeEqualTo(String value) {
            addCriterion("trade_type =", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotEqualTo(String value) {
            addCriterion("trade_type <>", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeGreaterThan(String value) {
            addCriterion("trade_type >", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("trade_type >=", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLessThan(String value) {
            addCriterion("trade_type <", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLessThanOrEqualTo(String value) {
            addCriterion("trade_type <=", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeLike(String value) {
            addCriterion("trade_type like", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotLike(String value) {
            addCriterion("trade_type not like", value, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeIn(List<String> values) {
            addCriterion("trade_type in", values, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotIn(List<String> values) {
            addCriterion("trade_type not in", values, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeBetween(String value1, String value2) {
            addCriterion("trade_type between", value1, value2, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeTypeNotBetween(String value1, String value2) {
            addCriterion("trade_type not between", value1, value2, "tradeType");
            return (Criteria) this;
        }

        public Criteria andTradeContentIsNull() {
            addCriterion("trade_content is null");
            return (Criteria) this;
        }

        public Criteria andTradeContentIsNotNull() {
            addCriterion("trade_content is not null");
            return (Criteria) this;
        }

        public Criteria andTradeContentEqualTo(String value) {
            addCriterion("trade_content =", value, "tradeContent");
            return (Criteria) this;
        }

        public Criteria andTradeContentNotEqualTo(String value) {
            addCriterion("trade_content <>", value, "tradeContent");
            return (Criteria) this;
        }

        public Criteria andTradeContentGreaterThan(String value) {
            addCriterion("trade_content >", value, "tradeContent");
            return (Criteria) this;
        }

        public Criteria andTradeContentGreaterThanOrEqualTo(String value) {
            addCriterion("trade_content >=", value, "tradeContent");
            return (Criteria) this;
        }

        public Criteria andTradeContentLessThan(String value) {
            addCriterion("trade_content <", value, "tradeContent");
            return (Criteria) this;
        }

        public Criteria andTradeContentLessThanOrEqualTo(String value) {
            addCriterion("trade_content <=", value, "tradeContent");
            return (Criteria) this;
        }

        public Criteria andTradeContentLike(String value) {
            addCriterion("trade_content like", value, "tradeContent");
            return (Criteria) this;
        }

        public Criteria andTradeContentNotLike(String value) {
            addCriterion("trade_content not like", value, "tradeContent");
            return (Criteria) this;
        }

        public Criteria andTradeContentIn(List<String> values) {
            addCriterion("trade_content in", values, "tradeContent");
            return (Criteria) this;
        }

        public Criteria andTradeContentNotIn(List<String> values) {
            addCriterion("trade_content not in", values, "tradeContent");
            return (Criteria) this;
        }

        public Criteria andTradeContentBetween(String value1, String value2) {
            addCriterion("trade_content between", value1, value2, "tradeContent");
            return (Criteria) this;
        }

        public Criteria andTradeContentNotBetween(String value1, String value2) {
            addCriterion("trade_content not between", value1, value2, "tradeContent");
            return (Criteria) this;
        }

        public Criteria andTradeStatusIsNull() {
            addCriterion("trade_status is null");
            return (Criteria) this;
        }

        public Criteria andTradeStatusIsNotNull() {
            addCriterion("trade_status is not null");
            return (Criteria) this;
        }

        public Criteria andTradeStatusEqualTo(String value) {
            addCriterion("trade_status =", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusNotEqualTo(String value) {
            addCriterion("trade_status <>", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusGreaterThan(String value) {
            addCriterion("trade_status >", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusGreaterThanOrEqualTo(String value) {
            addCriterion("trade_status >=", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusLessThan(String value) {
            addCriterion("trade_status <", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusLessThanOrEqualTo(String value) {
            addCriterion("trade_status <=", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusLike(String value) {
            addCriterion("trade_status like", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusNotLike(String value) {
            addCriterion("trade_status not like", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusIn(List<String> values) {
            addCriterion("trade_status in", values, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusNotIn(List<String> values) {
            addCriterion("trade_status not in", values, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusBetween(String value1, String value2) {
            addCriterion("trade_status between", value1, value2, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusNotBetween(String value1, String value2) {
            addCriterion("trade_status not between", value1, value2, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andRmrkIsNull() {
            addCriterion("rmrk is null");
            return (Criteria) this;
        }

        public Criteria andRmrkIsNotNull() {
            addCriterion("rmrk is not null");
            return (Criteria) this;
        }

        public Criteria andRmrkEqualTo(String value) {
            addCriterion("rmrk =", value, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkNotEqualTo(String value) {
            addCriterion("rmrk <>", value, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkGreaterThan(String value) {
            addCriterion("rmrk >", value, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkGreaterThanOrEqualTo(String value) {
            addCriterion("rmrk >=", value, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkLessThan(String value) {
            addCriterion("rmrk <", value, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkLessThanOrEqualTo(String value) {
            addCriterion("rmrk <=", value, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkLike(String value) {
            addCriterion("rmrk like", value, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkNotLike(String value) {
            addCriterion("rmrk not like", value, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkIn(List<String> values) {
            addCriterion("rmrk in", values, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkNotIn(List<String> values) {
            addCriterion("rmrk not in", values, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkBetween(String value1, String value2) {
            addCriterion("rmrk between", value1, value2, "rmrk");
            return (Criteria) this;
        }

        public Criteria andRmrkNotBetween(String value1, String value2) {
            addCriterion("rmrk not between", value1, value2, "rmrk");
            return (Criteria) this;
        }

        public Criteria andPayAcctNoIsNull() {
            addCriterion("pay_acct_no is null");
            return (Criteria) this;
        }

        public Criteria andPayAcctNoIsNotNull() {
            addCriterion("pay_acct_no is not null");
            return (Criteria) this;
        }

        public Criteria andPayAcctNoEqualTo(String value) {
            addCriterion("pay_acct_no =", value, "payAcctNo");
            return (Criteria) this;
        }

        public Criteria andPayAcctNoNotEqualTo(String value) {
            addCriterion("pay_acct_no <>", value, "payAcctNo");
            return (Criteria) this;
        }

        public Criteria andPayAcctNoGreaterThan(String value) {
            addCriterion("pay_acct_no >", value, "payAcctNo");
            return (Criteria) this;
        }

        public Criteria andPayAcctNoGreaterThanOrEqualTo(String value) {
            addCriterion("pay_acct_no >=", value, "payAcctNo");
            return (Criteria) this;
        }

        public Criteria andPayAcctNoLessThan(String value) {
            addCriterion("pay_acct_no <", value, "payAcctNo");
            return (Criteria) this;
        }

        public Criteria andPayAcctNoLessThanOrEqualTo(String value) {
            addCriterion("pay_acct_no <=", value, "payAcctNo");
            return (Criteria) this;
        }

        public Criteria andPayAcctNoLike(String value) {
            addCriterion("pay_acct_no like", value, "payAcctNo");
            return (Criteria) this;
        }

        public Criteria andPayAcctNoNotLike(String value) {
            addCriterion("pay_acct_no not like", value, "payAcctNo");
            return (Criteria) this;
        }

        public Criteria andPayAcctNoIn(List<String> values) {
            addCriterion("pay_acct_no in", values, "payAcctNo");
            return (Criteria) this;
        }

        public Criteria andPayAcctNoNotIn(List<String> values) {
            addCriterion("pay_acct_no not in", values, "payAcctNo");
            return (Criteria) this;
        }

        public Criteria andPayAcctNoBetween(String value1, String value2) {
            addCriterion("pay_acct_no between", value1, value2, "payAcctNo");
            return (Criteria) this;
        }

        public Criteria andPayAcctNoNotBetween(String value1, String value2) {
            addCriterion("pay_acct_no not between", value1, value2, "payAcctNo");
            return (Criteria) this;
        }

        public Criteria andPayIdIsNull() {
            addCriterion("pay_id is null");
            return (Criteria) this;
        }

        public Criteria andPayIdIsNotNull() {
            addCriterion("pay_id is not null");
            return (Criteria) this;
        }

        public Criteria andPayIdEqualTo(Long value) {
            addCriterion("pay_id =", value, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdNotEqualTo(Long value) {
            addCriterion("pay_id <>", value, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdGreaterThan(Long value) {
            addCriterion("pay_id >", value, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdGreaterThanOrEqualTo(Long value) {
            addCriterion("pay_id >=", value, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdLessThan(Long value) {
            addCriterion("pay_id <", value, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdLessThanOrEqualTo(Long value) {
            addCriterion("pay_id <=", value, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdIn(List<Long> values) {
            addCriterion("pay_id in", values, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdNotIn(List<Long> values) {
            addCriterion("pay_id not in", values, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdBetween(Long value1, Long value2) {
            addCriterion("pay_id between", value1, value2, "payId");
            return (Criteria) this;
        }

        public Criteria andPayIdNotBetween(Long value1, Long value2) {
            addCriterion("pay_id not between", value1, value2, "payId");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNull() {
            addCriterion("create_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNotNull() {
            addCriterion("create_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateIdEqualTo(Long value) {
            addCriterion("create_id =", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotEqualTo(Long value) {
            addCriterion("create_id <>", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThan(Long value) {
            addCriterion("create_id >", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("create_id >=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThan(Long value) {
            addCriterion("create_id <", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThanOrEqualTo(Long value) {
            addCriterion("create_id <=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdIn(List<Long> values) {
            addCriterion("create_id in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotIn(List<Long> values) {
            addCriterion("create_id not in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdBetween(Long value1, Long value2) {
            addCriterion("create_id between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotBetween(Long value1, Long value2) {
            addCriterion("create_id not between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("operator like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("operator not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyIdIsNull() {
            addCriterion("modify_id is null");
            return (Criteria) this;
        }

        public Criteria andModifyIdIsNotNull() {
            addCriterion("modify_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifyIdEqualTo(Long value) {
            addCriterion("modify_id =", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotEqualTo(Long value) {
            addCriterion("modify_id <>", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdGreaterThan(Long value) {
            addCriterion("modify_id >", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("modify_id >=", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLessThan(Long value) {
            addCriterion("modify_id <", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLessThanOrEqualTo(Long value) {
            addCriterion("modify_id <=", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdIn(List<Long> values) {
            addCriterion("modify_id in", values, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotIn(List<Long> values) {
            addCriterion("modify_id not in", values, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdBetween(Long value1, Long value2) {
            addCriterion("modify_id between", value1, value2, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotBetween(Long value1, Long value2) {
            addCriterion("modify_id not between", value1, value2, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("modifier is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("modifier is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("modifier =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("modifier <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("modifier >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("modifier >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("modifier <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("modifier <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("modifier like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("modifier not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("modifier in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("modifier not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("modifier between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("modifier not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyIpIsNull() {
            addCriterion("modify_ip is null");
            return (Criteria) this;
        }

        public Criteria andModifyIpIsNotNull() {
            addCriterion("modify_ip is not null");
            return (Criteria) this;
        }

        public Criteria andModifyIpEqualTo(String value) {
            addCriterion("modify_ip =", value, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpNotEqualTo(String value) {
            addCriterion("modify_ip <>", value, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpGreaterThan(String value) {
            addCriterion("modify_ip >", value, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpGreaterThanOrEqualTo(String value) {
            addCriterion("modify_ip >=", value, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpLessThan(String value) {
            addCriterion("modify_ip <", value, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpLessThanOrEqualTo(String value) {
            addCriterion("modify_ip <=", value, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpLike(String value) {
            addCriterion("modify_ip like", value, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpNotLike(String value) {
            addCriterion("modify_ip not like", value, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpIn(List<String> values) {
            addCriterion("modify_ip in", values, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpNotIn(List<String> values) {
            addCriterion("modify_ip not in", values, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpBetween(String value1, String value2) {
            addCriterion("modify_ip between", value1, value2, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpNotBetween(String value1, String value2) {
            addCriterion("modify_ip not between", value1, value2, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Byte value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Byte value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Byte value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Byte value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Byte value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Byte value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Byte> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Byte> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Byte value1, Byte value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Byte value1, Byte value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 20 16:33:15 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}