package net.xyt.payment.batch.entity.acctinfo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PayAcctInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    public PayAcctInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("pkid is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("pkid is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(Long value) {
            addCriterion("pkid =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(Long value) {
            addCriterion("pkid <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(Long value) {
            addCriterion("pkid >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(Long value) {
            addCriterion("pkid >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(Long value) {
            addCriterion("pkid <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(Long value) {
            addCriterion("pkid <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<Long> values) {
            addCriterion("pkid in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<Long> values) {
            addCriterion("pkid not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(Long value1, Long value2) {
            addCriterion("pkid between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(Long value1, Long value2) {
            addCriterion("pkid not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andExAcctNoIsNull() {
            addCriterion("ex_acct_no is null");
            return (Criteria) this;
        }

        public Criteria andExAcctNoIsNotNull() {
            addCriterion("ex_acct_no is not null");
            return (Criteria) this;
        }

        public Criteria andExAcctNoEqualTo(String value) {
            addCriterion("ex_acct_no =", value, "exAcctNo");
            return (Criteria) this;
        }

        public Criteria andExAcctNoNotEqualTo(String value) {
            addCriterion("ex_acct_no <>", value, "exAcctNo");
            return (Criteria) this;
        }

        public Criteria andExAcctNoGreaterThan(String value) {
            addCriterion("ex_acct_no >", value, "exAcctNo");
            return (Criteria) this;
        }

        public Criteria andExAcctNoGreaterThanOrEqualTo(String value) {
            addCriterion("ex_acct_no >=", value, "exAcctNo");
            return (Criteria) this;
        }

        public Criteria andExAcctNoLessThan(String value) {
            addCriterion("ex_acct_no <", value, "exAcctNo");
            return (Criteria) this;
        }

        public Criteria andExAcctNoLessThanOrEqualTo(String value) {
            addCriterion("ex_acct_no <=", value, "exAcctNo");
            return (Criteria) this;
        }

        public Criteria andExAcctNoLike(String value) {
            addCriterion("ex_acct_no like", value, "exAcctNo");
            return (Criteria) this;
        }

        public Criteria andExAcctNoNotLike(String value) {
            addCriterion("ex_acct_no not like", value, "exAcctNo");
            return (Criteria) this;
        }

        public Criteria andExAcctNoIn(List<String> values) {
            addCriterion("ex_acct_no in", values, "exAcctNo");
            return (Criteria) this;
        }

        public Criteria andExAcctNoNotIn(List<String> values) {
            addCriterion("ex_acct_no not in", values, "exAcctNo");
            return (Criteria) this;
        }

        public Criteria andExAcctNoBetween(String value1, String value2) {
            addCriterion("ex_acct_no between", value1, value2, "exAcctNo");
            return (Criteria) this;
        }

        public Criteria andExAcctNoNotBetween(String value1, String value2) {
            addCriterion("ex_acct_no not between", value1, value2, "exAcctNo");
            return (Criteria) this;
        }

        public Criteria andExAcctNameIsNull() {
            addCriterion("ex_acct_name is null");
            return (Criteria) this;
        }

        public Criteria andExAcctNameIsNotNull() {
            addCriterion("ex_acct_name is not null");
            return (Criteria) this;
        }

        public Criteria andExAcctNameEqualTo(String value) {
            addCriterion("ex_acct_name =", value, "exAcctName");
            return (Criteria) this;
        }

        public Criteria andExAcctNameNotEqualTo(String value) {
            addCriterion("ex_acct_name <>", value, "exAcctName");
            return (Criteria) this;
        }

        public Criteria andExAcctNameGreaterThan(String value) {
            addCriterion("ex_acct_name >", value, "exAcctName");
            return (Criteria) this;
        }

        public Criteria andExAcctNameGreaterThanOrEqualTo(String value) {
            addCriterion("ex_acct_name >=", value, "exAcctName");
            return (Criteria) this;
        }

        public Criteria andExAcctNameLessThan(String value) {
            addCriterion("ex_acct_name <", value, "exAcctName");
            return (Criteria) this;
        }

        public Criteria andExAcctNameLessThanOrEqualTo(String value) {
            addCriterion("ex_acct_name <=", value, "exAcctName");
            return (Criteria) this;
        }

        public Criteria andExAcctNameLike(String value) {
            addCriterion("ex_acct_name like", value, "exAcctName");
            return (Criteria) this;
        }

        public Criteria andExAcctNameNotLike(String value) {
            addCriterion("ex_acct_name not like", value, "exAcctName");
            return (Criteria) this;
        }

        public Criteria andExAcctNameIn(List<String> values) {
            addCriterion("ex_acct_name in", values, "exAcctName");
            return (Criteria) this;
        }

        public Criteria andExAcctNameNotIn(List<String> values) {
            addCriterion("ex_acct_name not in", values, "exAcctName");
            return (Criteria) this;
        }

        public Criteria andExAcctNameBetween(String value1, String value2) {
            addCriterion("ex_acct_name between", value1, value2, "exAcctName");
            return (Criteria) this;
        }

        public Criteria andExAcctNameNotBetween(String value1, String value2) {
            addCriterion("ex_acct_name not between", value1, value2, "exAcctName");
            return (Criteria) this;
        }

        public Criteria andExAcctTypeIsNull() {
            addCriterion("ex_acct_type is null");
            return (Criteria) this;
        }

        public Criteria andExAcctTypeIsNotNull() {
            addCriterion("ex_acct_type is not null");
            return (Criteria) this;
        }

        public Criteria andExAcctTypeEqualTo(String value) {
            addCriterion("ex_acct_type =", value, "exAcctType");
            return (Criteria) this;
        }

        public Criteria andExAcctTypeNotEqualTo(String value) {
            addCriterion("ex_acct_type <>", value, "exAcctType");
            return (Criteria) this;
        }

        public Criteria andExAcctTypeGreaterThan(String value) {
            addCriterion("ex_acct_type >", value, "exAcctType");
            return (Criteria) this;
        }

        public Criteria andExAcctTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ex_acct_type >=", value, "exAcctType");
            return (Criteria) this;
        }

        public Criteria andExAcctTypeLessThan(String value) {
            addCriterion("ex_acct_type <", value, "exAcctType");
            return (Criteria) this;
        }

        public Criteria andExAcctTypeLessThanOrEqualTo(String value) {
            addCriterion("ex_acct_type <=", value, "exAcctType");
            return (Criteria) this;
        }

        public Criteria andExAcctTypeLike(String value) {
            addCriterion("ex_acct_type like", value, "exAcctType");
            return (Criteria) this;
        }

        public Criteria andExAcctTypeNotLike(String value) {
            addCriterion("ex_acct_type not like", value, "exAcctType");
            return (Criteria) this;
        }

        public Criteria andExAcctTypeIn(List<String> values) {
            addCriterion("ex_acct_type in", values, "exAcctType");
            return (Criteria) this;
        }

        public Criteria andExAcctTypeNotIn(List<String> values) {
            addCriterion("ex_acct_type not in", values, "exAcctType");
            return (Criteria) this;
        }

        public Criteria andExAcctTypeBetween(String value1, String value2) {
            addCriterion("ex_acct_type between", value1, value2, "exAcctType");
            return (Criteria) this;
        }

        public Criteria andExAcctTypeNotBetween(String value1, String value2) {
            addCriterion("ex_acct_type not between", value1, value2, "exAcctType");
            return (Criteria) this;
        }

        public Criteria andOpenTimeIsNull() {
            addCriterion("open_time is null");
            return (Criteria) this;
        }

        public Criteria andOpenTimeIsNotNull() {
            addCriterion("open_time is not null");
            return (Criteria) this;
        }

        public Criteria andOpenTimeEqualTo(Date value) {
            addCriterion("open_time =", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeNotEqualTo(Date value) {
            addCriterion("open_time <>", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeGreaterThan(Date value) {
            addCriterion("open_time >", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("open_time >=", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeLessThan(Date value) {
            addCriterion("open_time <", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeLessThanOrEqualTo(Date value) {
            addCriterion("open_time <=", value, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeIn(List<Date> values) {
            addCriterion("open_time in", values, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeNotIn(List<Date> values) {
            addCriterion("open_time not in", values, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeBetween(Date value1, Date value2) {
            addCriterion("open_time between", value1, value2, "openTime");
            return (Criteria) this;
        }

        public Criteria andOpenTimeNotBetween(Date value1, Date value2) {
            addCriterion("open_time not between", value1, value2, "openTime");
            return (Criteria) this;
        }

        public Criteria andAcctStatusIsNull() {
            addCriterion("acct_status is null");
            return (Criteria) this;
        }

        public Criteria andAcctStatusIsNotNull() {
            addCriterion("acct_status is not null");
            return (Criteria) this;
        }

        public Criteria andAcctStatusEqualTo(String value) {
            addCriterion("acct_status =", value, "acctStatus");
            return (Criteria) this;
        }

        public Criteria andAcctStatusNotEqualTo(String value) {
            addCriterion("acct_status <>", value, "acctStatus");
            return (Criteria) this;
        }

        public Criteria andAcctStatusGreaterThan(String value) {
            addCriterion("acct_status >", value, "acctStatus");
            return (Criteria) this;
        }

        public Criteria andAcctStatusGreaterThanOrEqualTo(String value) {
            addCriterion("acct_status >=", value, "acctStatus");
            return (Criteria) this;
        }

        public Criteria andAcctStatusLessThan(String value) {
            addCriterion("acct_status <", value, "acctStatus");
            return (Criteria) this;
        }

        public Criteria andAcctStatusLessThanOrEqualTo(String value) {
            addCriterion("acct_status <=", value, "acctStatus");
            return (Criteria) this;
        }

        public Criteria andAcctStatusLike(String value) {
            addCriterion("acct_status like", value, "acctStatus");
            return (Criteria) this;
        }

        public Criteria andAcctStatusNotLike(String value) {
            addCriterion("acct_status not like", value, "acctStatus");
            return (Criteria) this;
        }

        public Criteria andAcctStatusIn(List<String> values) {
            addCriterion("acct_status in", values, "acctStatus");
            return (Criteria) this;
        }

        public Criteria andAcctStatusNotIn(List<String> values) {
            addCriterion("acct_status not in", values, "acctStatus");
            return (Criteria) this;
        }

        public Criteria andAcctStatusBetween(String value1, String value2) {
            addCriterion("acct_status between", value1, value2, "acctStatus");
            return (Criteria) this;
        }

        public Criteria andAcctStatusNotBetween(String value1, String value2) {
            addCriterion("acct_status not between", value1, value2, "acctStatus");
            return (Criteria) this;
        }

        public Criteria andTotalBalAmtIsNull() {
            addCriterion("total_bal_amt is null");
            return (Criteria) this;
        }

        public Criteria andTotalBalAmtIsNotNull() {
            addCriterion("total_bal_amt is not null");
            return (Criteria) this;
        }

        public Criteria andTotalBalAmtEqualTo(BigDecimal value) {
            addCriterion("total_bal_amt =", value, "totalBalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalBalAmtNotEqualTo(BigDecimal value) {
            addCriterion("total_bal_amt <>", value, "totalBalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalBalAmtGreaterThan(BigDecimal value) {
            addCriterion("total_bal_amt >", value, "totalBalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalBalAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_bal_amt >=", value, "totalBalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalBalAmtLessThan(BigDecimal value) {
            addCriterion("total_bal_amt <", value, "totalBalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalBalAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_bal_amt <=", value, "totalBalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalBalAmtIn(List<BigDecimal> values) {
            addCriterion("total_bal_amt in", values, "totalBalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalBalAmtNotIn(List<BigDecimal> values) {
            addCriterion("total_bal_amt not in", values, "totalBalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalBalAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_bal_amt between", value1, value2, "totalBalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalBalAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_bal_amt not between", value1, value2, "totalBalAmt");
            return (Criteria) this;
        }

        public Criteria andAviBalAmtIsNull() {
            addCriterion("avi_bal_amt is null");
            return (Criteria) this;
        }

        public Criteria andAviBalAmtIsNotNull() {
            addCriterion("avi_bal_amt is not null");
            return (Criteria) this;
        }

        public Criteria andAviBalAmtEqualTo(BigDecimal value) {
            addCriterion("avi_bal_amt =", value, "aviBalAmt");
            return (Criteria) this;
        }

        public Criteria andAviBalAmtNotEqualTo(BigDecimal value) {
            addCriterion("avi_bal_amt <>", value, "aviBalAmt");
            return (Criteria) this;
        }

        public Criteria andAviBalAmtGreaterThan(BigDecimal value) {
            addCriterion("avi_bal_amt >", value, "aviBalAmt");
            return (Criteria) this;
        }

        public Criteria andAviBalAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("avi_bal_amt >=", value, "aviBalAmt");
            return (Criteria) this;
        }

        public Criteria andAviBalAmtLessThan(BigDecimal value) {
            addCriterion("avi_bal_amt <", value, "aviBalAmt");
            return (Criteria) this;
        }

        public Criteria andAviBalAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("avi_bal_amt <=", value, "aviBalAmt");
            return (Criteria) this;
        }

        public Criteria andAviBalAmtIn(List<BigDecimal> values) {
            addCriterion("avi_bal_amt in", values, "aviBalAmt");
            return (Criteria) this;
        }

        public Criteria andAviBalAmtNotIn(List<BigDecimal> values) {
            addCriterion("avi_bal_amt not in", values, "aviBalAmt");
            return (Criteria) this;
        }

        public Criteria andAviBalAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avi_bal_amt between", value1, value2, "aviBalAmt");
            return (Criteria) this;
        }

        public Criteria andAviBalAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avi_bal_amt not between", value1, value2, "aviBalAmt");
            return (Criteria) this;
        }

        public Criteria andAviDrawAmtIsNull() {
            addCriterion("avi_draw_amt is null");
            return (Criteria) this;
        }

        public Criteria andAviDrawAmtIsNotNull() {
            addCriterion("avi_draw_amt is not null");
            return (Criteria) this;
        }

        public Criteria andAviDrawAmtEqualTo(BigDecimal value) {
            addCriterion("avi_draw_amt =", value, "aviDrawAmt");
            return (Criteria) this;
        }

        public Criteria andAviDrawAmtNotEqualTo(BigDecimal value) {
            addCriterion("avi_draw_amt <>", value, "aviDrawAmt");
            return (Criteria) this;
        }

        public Criteria andAviDrawAmtGreaterThan(BigDecimal value) {
            addCriterion("avi_draw_amt >", value, "aviDrawAmt");
            return (Criteria) this;
        }

        public Criteria andAviDrawAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("avi_draw_amt >=", value, "aviDrawAmt");
            return (Criteria) this;
        }

        public Criteria andAviDrawAmtLessThan(BigDecimal value) {
            addCriterion("avi_draw_amt <", value, "aviDrawAmt");
            return (Criteria) this;
        }

        public Criteria andAviDrawAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("avi_draw_amt <=", value, "aviDrawAmt");
            return (Criteria) this;
        }

        public Criteria andAviDrawAmtIn(List<BigDecimal> values) {
            addCriterion("avi_draw_amt in", values, "aviDrawAmt");
            return (Criteria) this;
        }

        public Criteria andAviDrawAmtNotIn(List<BigDecimal> values) {
            addCriterion("avi_draw_amt not in", values, "aviDrawAmt");
            return (Criteria) this;
        }

        public Criteria andAviDrawAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avi_draw_amt between", value1, value2, "aviDrawAmt");
            return (Criteria) this;
        }

        public Criteria andAviDrawAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avi_draw_amt not between", value1, value2, "aviDrawAmt");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNull() {
            addCriterion("create_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNotNull() {
            addCriterion("create_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateIdEqualTo(Long value) {
            addCriterion("create_id =", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotEqualTo(Long value) {
            addCriterion("create_id <>", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThan(Long value) {
            addCriterion("create_id >", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("create_id >=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThan(Long value) {
            addCriterion("create_id <", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThanOrEqualTo(Long value) {
            addCriterion("create_id <=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdIn(List<Long> values) {
            addCriterion("create_id in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotIn(List<Long> values) {
            addCriterion("create_id not in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdBetween(Long value1, Long value2) {
            addCriterion("create_id between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotBetween(Long value1, Long value2) {
            addCriterion("create_id not between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("operator like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("operator not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyIdIsNull() {
            addCriterion("modify_id is null");
            return (Criteria) this;
        }

        public Criteria andModifyIdIsNotNull() {
            addCriterion("modify_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifyIdEqualTo(Long value) {
            addCriterion("modify_id =", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotEqualTo(Long value) {
            addCriterion("modify_id <>", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdGreaterThan(Long value) {
            addCriterion("modify_id >", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("modify_id >=", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLessThan(Long value) {
            addCriterion("modify_id <", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLessThanOrEqualTo(Long value) {
            addCriterion("modify_id <=", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdIn(List<Long> values) {
            addCriterion("modify_id in", values, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotIn(List<Long> values) {
            addCriterion("modify_id not in", values, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdBetween(Long value1, Long value2) {
            addCriterion("modify_id between", value1, value2, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotBetween(Long value1, Long value2) {
            addCriterion("modify_id not between", value1, value2, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("modifier is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("modifier is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("modifier =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("modifier <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("modifier >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("modifier >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("modifier <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("modifier <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("modifier like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("modifier not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("modifier in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("modifier not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("modifier between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("modifier not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyIpIsNull() {
            addCriterion("modify_ip is null");
            return (Criteria) this;
        }

        public Criteria andModifyIpIsNotNull() {
            addCriterion("modify_ip is not null");
            return (Criteria) this;
        }

        public Criteria andModifyIpEqualTo(String value) {
            addCriterion("modify_ip =", value, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpNotEqualTo(String value) {
            addCriterion("modify_ip <>", value, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpGreaterThan(String value) {
            addCriterion("modify_ip >", value, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpGreaterThanOrEqualTo(String value) {
            addCriterion("modify_ip >=", value, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpLessThan(String value) {
            addCriterion("modify_ip <", value, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpLessThanOrEqualTo(String value) {
            addCriterion("modify_ip <=", value, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpLike(String value) {
            addCriterion("modify_ip like", value, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpNotLike(String value) {
            addCriterion("modify_ip not like", value, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpIn(List<String> values) {
            addCriterion("modify_ip in", values, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpNotIn(List<String> values) {
            addCriterion("modify_ip not in", values, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpBetween(String value1, String value2) {
            addCriterion("modify_ip between", value1, value2, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andModifyIpNotBetween(String value1, String value2) {
            addCriterion("modify_ip not between", value1, value2, "modifyIp");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Byte value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Byte value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Byte value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Byte value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Byte value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Byte value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Byte> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Byte> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Byte value1, Byte value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Byte value1, Byte value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_acct_info
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 20 15:14:52 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}