package net.xyt.payment.batch.mapper.transpay;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import net.xyt.payment.batch.entity.transpay.PayTransPayRecord;
import net.xyt.payment.batch.entity.transpay.PayTransPayRecordExample;
@Mapper
public interface PayTransPayRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_pay_record
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    long countByExample(PayTransPayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_pay_record
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    int deleteByExample(PayTransPayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_pay_record
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    int deleteByPrimaryKey(Long pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_pay_record
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    int insert(PayTransPayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_pay_record
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    int insertSelective(PayTransPayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_pay_record
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    List<PayTransPayRecord> selectByExample(PayTransPayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_pay_record
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    PayTransPayRecord selectByPrimaryKey(Long pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_pay_record
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") PayTransPayRecord record, @Param("example") PayTransPayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_pay_record
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    int updateByExample(@Param("record") PayTransPayRecord record, @Param("example") PayTransPayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_pay_record
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    int updateByPrimaryKeySelective(PayTransPayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_pay_record
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    int updateByPrimaryKey(PayTransPayRecord record);
}