package net.xyt.payment.batch.mapper.transrcv;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import net.xyt.payment.batch.entity.transrcv.PayTransRcvRecord;
import net.xyt.payment.batch.entity.transrcv.PayTransRcvRecordExample;
@Mapper
public interface PayTransRcvRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    long countByExample(PayTransRcvRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    int deleteByExample(PayTransRcvRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    int insert(PayTransRcvRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    int insertSelective(PayTransRcvRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    List<PayTransRcvRecord> selectByExample(PayTransRcvRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") PayTransRcvRecord record, @Param("example") PayTransRcvRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_trans_rcv_record
     *
     * @mbg.generated Thu Jun 20 16:33:15 CST 2019
     */
    int updateByExample(@Param("record") PayTransRcvRecord record, @Param("example") PayTransRcvRecordExample example);
}