package net.xyt.payment.batch.entity.acctdetail;

import java.math.BigDecimal;
import java.util.Date;

public class PayAcctDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.pkid
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private Long pkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.flow_no
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private String flowNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.ex_acct_no
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private String exAcctNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.trade_type
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private String tradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.trade_amt
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private BigDecimal tradeAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.trade_time
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private Date tradeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.redirect
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private Integer redirect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.acct_balance
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private BigDecimal acctBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.avi_use_bal
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private BigDecimal aviUseBal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.avi_draw_bal
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private BigDecimal aviDrawBal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.rmrk
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private String rmrk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.create_id
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.operator
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.create_time
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.modify_id
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private Long modifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.modifier
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.modify_time
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.modify_ip
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private String modifyIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_acct_detail.deleted
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    private Byte deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.pkid
     *
     * @return the value of pay_acct_detail.pkid
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public Long getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.pkid
     *
     * @param pkid the value for pay_acct_detail.pkid
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setPkid(Long pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.flow_no
     *
     * @return the value of pay_acct_detail.flow_no
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public String getFlowNo() {
        return flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.flow_no
     *
     * @param flowNo the value for pay_acct_detail.flow_no
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setFlowNo(String flowNo) {
        this.flowNo = flowNo == null ? null : flowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.ex_acct_no
     *
     * @return the value of pay_acct_detail.ex_acct_no
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public String getExAcctNo() {
        return exAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.ex_acct_no
     *
     * @param exAcctNo the value for pay_acct_detail.ex_acct_no
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setExAcctNo(String exAcctNo) {
        this.exAcctNo = exAcctNo == null ? null : exAcctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.trade_type
     *
     * @return the value of pay_acct_detail.trade_type
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.trade_type
     *
     * @param tradeType the value for pay_acct_detail.trade_type
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.trade_amt
     *
     * @return the value of pay_acct_detail.trade_amt
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public BigDecimal getTradeAmt() {
        return tradeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.trade_amt
     *
     * @param tradeAmt the value for pay_acct_detail.trade_amt
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setTradeAmt(BigDecimal tradeAmt) {
        this.tradeAmt = tradeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.trade_time
     *
     * @return the value of pay_acct_detail.trade_time
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public Date getTradeTime() {
        return tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.trade_time
     *
     * @param tradeTime the value for pay_acct_detail.trade_time
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setTradeTime(Date tradeTime) {
        this.tradeTime = tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.redirect
     *
     * @return the value of pay_acct_detail.redirect
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public Integer getRedirect() {
        return redirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.redirect
     *
     * @param redirect the value for pay_acct_detail.redirect
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setRedirect(Integer redirect) {
        this.redirect = redirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.acct_balance
     *
     * @return the value of pay_acct_detail.acct_balance
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public BigDecimal getAcctBalance() {
        return acctBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.acct_balance
     *
     * @param acctBalance the value for pay_acct_detail.acct_balance
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setAcctBalance(BigDecimal acctBalance) {
        this.acctBalance = acctBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.avi_use_bal
     *
     * @return the value of pay_acct_detail.avi_use_bal
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public BigDecimal getAviUseBal() {
        return aviUseBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.avi_use_bal
     *
     * @param aviUseBal the value for pay_acct_detail.avi_use_bal
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setAviUseBal(BigDecimal aviUseBal) {
        this.aviUseBal = aviUseBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.avi_draw_bal
     *
     * @return the value of pay_acct_detail.avi_draw_bal
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public BigDecimal getAviDrawBal() {
        return aviDrawBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.avi_draw_bal
     *
     * @param aviDrawBal the value for pay_acct_detail.avi_draw_bal
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setAviDrawBal(BigDecimal aviDrawBal) {
        this.aviDrawBal = aviDrawBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.rmrk
     *
     * @return the value of pay_acct_detail.rmrk
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public String getRmrk() {
        return rmrk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.rmrk
     *
     * @param rmrk the value for pay_acct_detail.rmrk
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk == null ? null : rmrk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.create_id
     *
     * @return the value of pay_acct_detail.create_id
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.create_id
     *
     * @param createId the value for pay_acct_detail.create_id
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.operator
     *
     * @return the value of pay_acct_detail.operator
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.operator
     *
     * @param operator the value for pay_acct_detail.operator
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.create_time
     *
     * @return the value of pay_acct_detail.create_time
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.create_time
     *
     * @param createTime the value for pay_acct_detail.create_time
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.modify_id
     *
     * @return the value of pay_acct_detail.modify_id
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public Long getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.modify_id
     *
     * @param modifyId the value for pay_acct_detail.modify_id
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setModifyId(Long modifyId) {
        this.modifyId = modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.modifier
     *
     * @return the value of pay_acct_detail.modifier
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.modifier
     *
     * @param modifier the value for pay_acct_detail.modifier
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.modify_time
     *
     * @return the value of pay_acct_detail.modify_time
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.modify_time
     *
     * @param modifyTime the value for pay_acct_detail.modify_time
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.modify_ip
     *
     * @return the value of pay_acct_detail.modify_ip
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public String getModifyIp() {
        return modifyIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.modify_ip
     *
     * @param modifyIp the value for pay_acct_detail.modify_ip
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setModifyIp(String modifyIp) {
        this.modifyIp = modifyIp == null ? null : modifyIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_acct_detail.deleted
     *
     * @return the value of pay_acct_detail.deleted
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_acct_detail.deleted
     *
     * @param deleted the value for pay_acct_detail.deleted
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }
}