package net.xyt.payment.batch.mapper.acctdetail;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import net.xyt.payment.batch.entity.acctdetail.PayAcctDetail;
import net.xyt.payment.batch.entity.acctdetail.PayAcctDetailExample;
@Mapper
public interface PayAcctDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_detail
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    long countByExample(PayAcctDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_detail
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    int deleteByExample(PayAcctDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_detail
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    int deleteByPrimaryKey(Long pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_detail
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    int insert(PayAcctDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_detail
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    int insertSelective(PayAcctDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_detail
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    List<PayAcctDetail> selectByExample(PayAcctDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_detail
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    PayAcctDetail selectByPrimaryKey(Long pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_detail
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") PayAcctDetail record, @Param("example") PayAcctDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_detail
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    int updateByExample(@Param("record") PayAcctDetail record, @Param("example") PayAcctDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_detail
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    int updateByPrimaryKeySelective(PayAcctDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_detail
     *
     * @mbg.generated Mon Jul 08 17:38:33 CST 2019
     */
    int updateByPrimaryKey(PayAcctDetail record);
}