package net.xyt.payment.batch.entity.transpay;

import java.math.BigDecimal;
import java.util.Date;

public class PayTransPayRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.pkid
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private Long pkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.flow_no
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private String flowNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.platform_code
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private String platformCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.pay_acct_no
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private String payAcctNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.pay_trans_amt
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private BigDecimal payTransAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.fee_amt
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private BigDecimal feeAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.fee_rate
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private BigDecimal feeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.trade_type
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private String tradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.trade_content
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private String tradeContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.trade_status
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private String tradeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.rmrk
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private String rmrk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.create_id
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.operator
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.create_time
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.modify_id
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private Long modifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.modifier
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.modify_time
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.modify_ip
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private String modifyIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_trans_pay_record.deleted
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    private Byte deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.pkid
     *
     * @return the value of pay_trans_pay_record.pkid
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public Long getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.pkid
     *
     * @param pkid the value for pay_trans_pay_record.pkid
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setPkid(Long pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.flow_no
     *
     * @return the value of pay_trans_pay_record.flow_no
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public String getFlowNo() {
        return flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.flow_no
     *
     * @param flowNo the value for pay_trans_pay_record.flow_no
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setFlowNo(String flowNo) {
        this.flowNo = flowNo == null ? null : flowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.platform_code
     *
     * @return the value of pay_trans_pay_record.platform_code
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public String getPlatformCode() {
        return platformCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.platform_code
     *
     * @param platformCode the value for pay_trans_pay_record.platform_code
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setPlatformCode(String platformCode) {
        this.platformCode = platformCode == null ? null : platformCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.pay_acct_no
     *
     * @return the value of pay_trans_pay_record.pay_acct_no
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public String getPayAcctNo() {
        return payAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.pay_acct_no
     *
     * @param payAcctNo the value for pay_trans_pay_record.pay_acct_no
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setPayAcctNo(String payAcctNo) {
        this.payAcctNo = payAcctNo == null ? null : payAcctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.pay_trans_amt
     *
     * @return the value of pay_trans_pay_record.pay_trans_amt
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public BigDecimal getPayTransAmt() {
        return payTransAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.pay_trans_amt
     *
     * @param payTransAmt the value for pay_trans_pay_record.pay_trans_amt
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setPayTransAmt(BigDecimal payTransAmt) {
        this.payTransAmt = payTransAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.fee_amt
     *
     * @return the value of pay_trans_pay_record.fee_amt
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public BigDecimal getFeeAmt() {
        return feeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.fee_amt
     *
     * @param feeAmt the value for pay_trans_pay_record.fee_amt
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setFeeAmt(BigDecimal feeAmt) {
        this.feeAmt = feeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.fee_rate
     *
     * @return the value of pay_trans_pay_record.fee_rate
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public BigDecimal getFeeRate() {
        return feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.fee_rate
     *
     * @param feeRate the value for pay_trans_pay_record.fee_rate
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setFeeRate(BigDecimal feeRate) {
        this.feeRate = feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.trade_type
     *
     * @return the value of pay_trans_pay_record.trade_type
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.trade_type
     *
     * @param tradeType the value for pay_trans_pay_record.trade_type
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.trade_content
     *
     * @return the value of pay_trans_pay_record.trade_content
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public String getTradeContent() {
        return tradeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.trade_content
     *
     * @param tradeContent the value for pay_trans_pay_record.trade_content
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setTradeContent(String tradeContent) {
        this.tradeContent = tradeContent == null ? null : tradeContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.trade_status
     *
     * @return the value of pay_trans_pay_record.trade_status
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public String getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.trade_status
     *
     * @param tradeStatus the value for pay_trans_pay_record.trade_status
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setTradeStatus(String tradeStatus) {
        this.tradeStatus = tradeStatus == null ? null : tradeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.rmrk
     *
     * @return the value of pay_trans_pay_record.rmrk
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public String getRmrk() {
        return rmrk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.rmrk
     *
     * @param rmrk the value for pay_trans_pay_record.rmrk
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk == null ? null : rmrk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.create_id
     *
     * @return the value of pay_trans_pay_record.create_id
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.create_id
     *
     * @param createId the value for pay_trans_pay_record.create_id
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.operator
     *
     * @return the value of pay_trans_pay_record.operator
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.operator
     *
     * @param operator the value for pay_trans_pay_record.operator
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.create_time
     *
     * @return the value of pay_trans_pay_record.create_time
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.create_time
     *
     * @param createTime the value for pay_trans_pay_record.create_time
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.modify_id
     *
     * @return the value of pay_trans_pay_record.modify_id
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public Long getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.modify_id
     *
     * @param modifyId the value for pay_trans_pay_record.modify_id
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setModifyId(Long modifyId) {
        this.modifyId = modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.modifier
     *
     * @return the value of pay_trans_pay_record.modifier
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.modifier
     *
     * @param modifier the value for pay_trans_pay_record.modifier
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.modify_time
     *
     * @return the value of pay_trans_pay_record.modify_time
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.modify_time
     *
     * @param modifyTime the value for pay_trans_pay_record.modify_time
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.modify_ip
     *
     * @return the value of pay_trans_pay_record.modify_ip
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public String getModifyIp() {
        return modifyIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.modify_ip
     *
     * @param modifyIp the value for pay_trans_pay_record.modify_ip
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setModifyIp(String modifyIp) {
        this.modifyIp = modifyIp == null ? null : modifyIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_trans_pay_record.deleted
     *
     * @return the value of pay_trans_pay_record.deleted
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_trans_pay_record.deleted
     *
     * @param deleted the value for pay_trans_pay_record.deleted
     *
     * @mbg.generated Thu Jun 20 16:29:15 CST 2019
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }
}