package net.xyt.payment.batch.mapper.acctinfo;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import net.xyt.payment.batch.entity.acctinfo.PayAcctInfo;
import net.xyt.payment.batch.entity.acctinfo.PayAcctInfoExample;
@Mapper
public interface PayAcctInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    long countByExample(PayAcctInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    int deleteByExample(PayAcctInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    int deleteByPrimaryKey(Long pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    int insert(PayAcctInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    int insertSelective(PayAcctInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    List<PayAcctInfo> selectByExample(PayAcctInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    PayAcctInfo selectByPrimaryKey(Long pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") PayAcctInfo record, @Param("example") PayAcctInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    int updateByExample(@Param("record") PayAcctInfo record, @Param("example") PayAcctInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    int updateByPrimaryKeySelective(PayAcctInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_acct_info
     *
     * @mbg.generated Thu Jun 20 15:14:52 CST 2019
     */
    int updateByPrimaryKey(PayAcctInfo record);
}